//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stock.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Aha_Soft_Universal_Shop_Print {
            get {
                object obj = ResourceManager.GetObject("Aha-Soft-Universal-Shop-Print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Aha_Soft_Universal_Shop_Print1 {
            get {
                object obj = ResourceManager.GetObject("Aha-Soft-Universal-Shop-Print1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Apathae_Chakram_2_Folder_Download {
            get {
                object obj = ResourceManager.GetObject("Apathae-Chakram-2-Folder-Download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Apathae_Chakram_2_Folder_Download1 {
            get {
                object obj = ResourceManager.GetObject("Apathae-Chakram-2-Folder-Download1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Custom_Icon_Design_Flatastic_4_Add_item {
            get {
                object obj = ResourceManager.GetObject("Custom-Icon-Design-Flatastic-4-Add-item", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Custom_Icon_Design_Flatastic_4_Add_item1 {
            get {
                object obj = ResourceManager.GetObject("Custom-Icon-Design-Flatastic-4-Add-item1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Custom_Icon_Design_Pretty_Office_9_Delete_file {
            get {
                object obj = ResourceManager.GetObject("Custom-Icon-Design-Pretty-Office-9-Delete-file", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Designcontest_Ecommerce_Business_Store {
            get {
                object obj = ResourceManager.GetObject("Designcontest-Ecommerce-Business-Store", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Designcontest_Ecommerce_Business_Store1 {
            get {
                object obj = ResourceManager.GetObject("Designcontest-Ecommerce-Business-Store1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Double_J_Design_Ravenna_3d_Settings {
            get {
                object obj = ResourceManager.GetObject("Double-J-Design-Ravenna-3d-Settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Everaldo_Kids_Icons_View_text {
            get {
                object obj = ResourceManager.GetObject("Everaldo-Kids-Icons-View-text", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Everaldo_Kids_Icons_View_text1 {
            get {
                object obj = ResourceManager.GetObject("Everaldo-Kids-Icons-View-text1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Hamzasaleem_Stock_Folder_Folder_Downloads {
            get {
                object obj = ResourceManager.GetObject("Hamzasaleem-Stock-Folder-Folder-Downloads", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Hopstarter_Mac_Folders_Blue_Download {
            get {
                object obj = ResourceManager.GetObject("Hopstarter-Mac-Folders-Blue-Download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Hopstarter_Sleek_Xp_Basic_Zoom {
            get {
                object obj = ResourceManager.GetObject("Hopstarter-Sleek-Xp-Basic-Zoom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Hopstarter_Soft_Scraps_Edit_Document {
            get {
                object obj = ResourceManager.GetObject("Hopstarter-Soft-Scraps-Edit-Document", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Hopstarter_Soft_Scraps_File_Delete {
            get {
                object obj = ResourceManager.GetObject("Hopstarter-Soft-Scraps-File-Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icojam_Blue_Bits_User_add {
            get {
                object obj = ResourceManager.GetObject("Icojam-Blue-Bits-User-add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icojam_Blue_Bits_User_delete {
            get {
                object obj = ResourceManager.GetObject("Icojam-Blue-Bits-User-delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icojam_Blue_Bits_User_search {
            get {
                object obj = ResourceManager.GetObject("Icojam-Blue-Bits-User-search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icojam_Blue_Bits_User_settings {
            get {
                object obj = ResourceManager.GetObject("Icojam-Blue-Bits-User-settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icojam_Blue_Bits_User_settings1 {
            get {
                object obj = ResourceManager.GetObject("Icojam-Blue-Bits-User-settings1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap login01 {
            get {
                object obj = ResourceManager.GetObject("login01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap members {
            get {
                object obj = ResourceManager.GetObject("members", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Oxygen_Icons_org_Oxygen_Actions_window_close {
            get {
                object obj = ResourceManager.GetObject("Oxygen-Icons.org-Oxygen-Actions-window-close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Oxygen_Icons_org_Oxygen_Apps_system_software_update {
            get {
                object obj = ResourceManager.GetObject("Oxygen-Icons.org-Oxygen-Apps-system-software-update", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap security {
            get {
                object obj = ResourceManager.GetObject("security", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Zerode_Plump_Search {
            get {
                object obj = ResourceManager.GetObject("Zerode-Plump-Search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
